// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Name string `json:"name"`
}

type Todo struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
