name: ci-server

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# concurrency 설명
# https://yceffort.kr/2021/09/github-ci-workflow-for-frontend-developer#%EB%B0%98%EB%B3%B5-%EC%9E%91%EC%97%85-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0
concurrency:
  # branch 를 기준할때: refs/heads/main
  # PR 을 기준할때: refs/pull/<pr_number>/merge
  # tag 를 기준할때: refs/tags/<tag_name>

  # workflow 의 그룹을 각 ${{ github.workflow }}-${{ github.ref }} 로 정의한다.
  # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
  group: ${{ github.workflow }}-${{ github.ref }}
  # 새로운 workflow 가 실행될때, 이미 실행중인 workflow 가 있다면, 해당 workflow 를 취소한다.
  cancel-in-progress: true

jobs:
  verify:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: generate gql code before verify
        run: make -C server/ gen

      - run: |
          go install golang.org/x/tools/cmd/goimports@latest
          make -C server/ verify
  lint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
#      - name: set up OSS credential
#        run: git config --global url.https://${OSS_TOKEN}@oss.navercorp.com/.insteadOf https://oss.navercorp.com/

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: generate gql code before lint
        run: make -C server/ gen

      - uses: golangci-lint-action@v3.1.0
        with:
          version: v1.45.2
          working-directory: server
  build:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
#      - name: set up OSS credential
#        run: git config --global url.https://${OSS_TOKEN}@oss.navercorp.com/.insteadOf https://oss.navercorp.com/

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: generate gql code before build
        run: make -C server/ gen

      - run: make -C server/ build

